#
# rcsid $Header: /usr/cvsroot/magic-8.0/wiring/Makefile,v 1.1.1.1 2008/02/03 20:43:50 tim Exp $
#

MODULE    = wiring
MAGICDIR  = ..
SRCS      = wireOps.c wireTech.c wireUndo.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
