#
# rscid $Header:
#

MODULE    = grouter
MAGICDIR  = ..
SRCS      = grouteChan.c grouteCrss.c grouteDens.c grouteMain.c \
            grouteMult.c grouteMaze.c groutePath.c groutePen.c grouteTest.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
