#
# rcsid $Header: /usr/cvsroot/magic-8.0/textio/Makefile,v 1.1.1.1 2008/02/03 20:43:50 tim Exp $
#

MODULE    = textio
MAGICDIR  = ..
SRCS      = txCommands.c txInput.c txMain.c txMore.c txOutput.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
