#
# rscid $Header:
#

MODULE    = resis
MAGICDIR  = ..
SRCS      = ResMain.c ResJunct.c ResMakeRes.c ResSimple.c ResPrint.c \
            ResReadSim.c ResConDCS.c ResRex.c ResBasic.c ResMerge.c ResChecks.c \
            ResFract.c ResUtils.c ResDebug.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
