#
# rcsid "$Header: /usr/cvsroot/magic-8.0/extract/Makefile,v 1.1.1.1 2008/02/03 20:43:50 tim Exp $"
#

MODULE    = extract
MAGICDIR  = ..
SRCS      = ExtArray.c ExtBasic.c ExtCell.c ExtCouple.c ExtHard.c \
            ExtHier.c ExtLength.c ExtMain.c ExtNghbors.c ExtPerim.c \
            ExtRegion.c ExtSubtree.c ExtTech.c ExtTest.c ExtTimes.c ExtYank.c \
            ExtInter.c ExtUnique.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
