#
# rcsid="$Header: /usr/cvsroot/magic-8.0/select/Makefile,v 1.1.1.1 2008/02/03 20:43:50 tim Exp $"
#

MODULE    = select
MAGICDIR  = ..
SRCS      = selCreate.c selDisplay.c selEnum.c selOps.c selUndo.c \
            selUnselect.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
