#
# rcsid $Header: /usr/cvsroot/magic-8.0/garouter/Makefile,v 1.1.1.1 2008/02/03 20:43:50 tim Exp $
#

MODULE    = garouter
MAGICDIR  = ..
SRCS      = gaChannel.c gaMain.c gaMaze.c gaSimple.c gaStem.c \
            gaTest.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
