#
# rcsid $Header: /usr/cvsroot/magic-8.0/plow/Makefile,v 1.1.1.1 2008/02/03 20:43:50 tim Exp $
#

MODULE    = plow
MAGICDIR  = ..
SRCS      = PlowCmd.c PlowJogs.c PlowMain.c PlowQueue.c PlowRandom.c \
            PlowRules1.c PlowRules2.c PlowRules3.c PlowSearch.c PlowTech.c \
            PlowTest.c PlowWidth.c PlowYank.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
